version: '3.9'

# You must manually run `ankerctl config import` atleast once
# docker run \
# -v ankerctl_vol:/root/.config/ankerctl \
# -v "$HOME/Library/Application Support/AnkerMake/AnkerMake_64bit_fp/login.json:/tmp/login.json" \
# ankerctl config import /tmp/login.json
services:
  nginx:
    image: nginx:latest
    container_name: ankerctl_nginx
    restart: unless-stopped
    volumes:
      - ./templates/docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:4470:4470
    depends_on:
      - ankerctl
  ankerctl:
    image: ankerctl/ankerctl:latest
    container_name: ankerctl
    restart: unless-stopped
    build: .
    environment:
      - FLASK_PORT=5000
      - FLASK_HOST=0.0.0.0
    volumes:
      - ankerctl_vol:/root/.config/ankerctl
    expose:
      - 5000
    entrypoint: "/app/ankerctl.py"
    command: ["webserver", "run"]

volumes:
  ankerctl_vol:
    external: true
