# You must manually run `ankerctl config import` atleast once
# docker run \
# -v ankerctl_vol:/root/.config/ankerctl \
# -v "$HOME/Library/Application Support/AnkerMake/AnkerMake_64bit_fp/login.json:/tmp/login.json" \
# ankerctl config import /tmp/login.json
services:
    ankerctl:
        image: ankerctl/ankerctl:latest
        container_name: ankerctl
        restart: unless-stopped
        build: .

        # host-mode networking is required for pppp communication with the
        # printer, since it is an asymmetrical udp protocol.
        network_mode: host

        # bind to localhost by default
        environment:
            - FLASK_HOST=127.0.0.1
            - FLASK_PORT=4470
        volumes:
            - ankerctl_vol:/root/.config/ankerctl

volumes:
    ankerctl_vol:
